export const newWithdraw = async () => {
    try {

    } catch (error) {
        throw new Error('خطای ناشناخته')
    }
}
